name: Test Collector
description: Uploads your JSON or JUnit files to Buildkite Test Analytics
author: https://github.com/buildkite
requirements:
  - curl
configuration:
  properties:
    api-token-env-name:
      type: string
    api-url:
      type: string
    base-path:
      type: string
    branches:
      type: string
    debug:
      type: boolean
    exclude-branches:
      type: string
    files:
      oneOf:
        - type: string
        - type: array
          items:
            type: string
    follow-symlinks:
      type: boolean
    format:
      enum:
        - json
        - junit
    missing-error:
      type: integer
    timeout:
      type: integer
    annotation-link:
      type: boolean
    concurrent-uploads:
      type: integer
  required:
    - files
    - format
  additionalProperties: false
