#!/bin/bash
set -euo pipefail

if [ "${BUILDKITE_PLUGIN_TEST_COLLECTOR_HOOK:-}" != "post-command" ]; then
  exit 0
fi

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/shared.bash
. "$DIR/../lib/shared.bash"
